/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FastCampusLecture.WAS.practice;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
